#!/bin/sh

for command in mount umount pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI"

alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"

alias \
	ka="killall" \
	g="git" \
	gst="git status" \
	gk="gitk" \
	e="$EDITOR" \
	v="$EDITOR" \
	gv="gvim" \
	t="tmux" \
	p="pacman"
