packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
call minpac#add('lifepillar/vim-solarized8', {'type': 'opt'})
call minpac#add('tpope/vim-sensible')
call minpac#add('tpope/vim-fugitive')
call minpac#add('tpope/vim-unimpaired')
call minpac#add('tpope/vim-vinegar')
call minpac#add('tpope/vim-surround')
call minpac#add('tpope/vim-surround')
call minpac#add('tpope/vim-commentary')
call minpac#add('junegunn/fzf.vim')
call minpac#add('vim-airline/vim-airline')
call minpac#add('vim-airline/vim-airline-themes')
call minpac#add('dense-analysis/ale')
call minpac#add('ap/vim-css-color')
call minpac#add('sheerun/vim-polyglot')
call minpac#add('iamcco/markdown-preview.nvim', {'do': 'packloadall! | call mkdp#util#install()'})

nnoremap <C-p> :<C-u>Files<CR>

let g:netrw_liststyle=3
let g:netrw_banner=0
let g:netrw_winsize=15
let g:netrw_browse_split=4

let g:airline_theme='sol'
let g:airline_experimental = 1

let g:ale_linters = {
			\ 'javascript': ['eslint'],
			\ 'java': ['javac'],
			\ }

nmap <silent> [W <Plug>(ale_first)
nmap <silent> [w <Plug>(ale_previous)
nmap <silent> ]w <Plug>(ale_next)
nmap <silent> ]W <Plug>(ale_last)

set background=light
colorscheme solarized8

set viminfofile=~/.vim/viminfo

command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()
